#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/auth-tokens

api_refresh_token:
    path: /api/auth-refresh
    controller: gesdinet.jwtrefreshtoken::refresh
